language: python
python:
  - "3.4"
install:
  - cd contacts
  - pip install -r requirements.txt
  - pip install coveralls
  - cd ..
script:
  - cd contacts
  - nosetests --with-coverage
after_success:
  - cd contacts
  - coveralls
